// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addLotsOfWeirdIssues', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addLotsOfWeirdIssues', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("coucou")
    await driver.findElement(By.id("password")).sendKeys("h")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("li:nth-child(2) .list-inline-item > .btn")).click()
    await driver.findElement(By.linkText("Issues")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("I1")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("LOW")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("i1")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("I2")
    await driver.findElement(By.id("headingAddIssue")).click()
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("0")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-1")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-2")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-3")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issuePriority")).sendKeys("HIGH")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("Bonjour")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("I4")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("6")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("7")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("8")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("9")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("10")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("11")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("12")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("13")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("14")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("15")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("16")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("17")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("18")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("19")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("20")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("21")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("22")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("23")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("24")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("25")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("26")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("27")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("28")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("29")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("30")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("31")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("32")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("33")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("34")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("35")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("MEDIUM")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("High difficulty")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("gjckjsvcuzqdjxiaqeoudjeoùz^f duevg4r6z8\'gmrihgrziof4sfresgh")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("LOW")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("strange name")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("Strange description")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("nfioezhfez#mofjoierjf56853258fnlekzjfgzuhfnfe4r6z4f5e64f8zr4fsz4fznjzehuifeè_-{}[]()%BGFHMOOYbffhb")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("LOW")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("Strange name 2")
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("#\"[]{(})%;?!ùmjkpohozef185.fe63tez57grnljgzjpané&hk,fs_-=°njk")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("6")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issuePriority")).sendKeys("HIGH")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("Strang name3")
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("é#{([])}+--_?;!|ù%è")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issuePriority")).sendKeys("LOW")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("123646898798597987899856568979878979798798746451312315646*/-+")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("0")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-6")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-7")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-8")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-9")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-10")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-11")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-12")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-13")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-14")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-15")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-16")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-17")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-18")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-19")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-20")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-21")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-22")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-23")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-24")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-25")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("medium")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("Strange name again")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Issues")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("123456779952599562")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("Many numbers")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-6")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-7")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-8")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-9")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-10")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issuePriority")).sendKeys("medium")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("abcdefghijklmnopqrstuvwxyzABCDJPÖHUJH")
    await driver.findElement(By.id("headingAddIssue")).click()
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("0")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-1")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-2")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-3")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-4")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-5")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-6")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-7")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-8")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-9")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-10")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-11")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-12")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-13")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-14")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-15")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-16")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-17")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-18")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-19")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-20")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-21")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-22")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-23")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("-24")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("medium")
    await driver.findElement(By.css("#collapseAddIssue .list-group-item:nth-child(1)")).click()
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("hyjutrz")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.id("issueName")).sendKeys("{(]-_|}[)")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("{(]-_|}[)")
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("2")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("3")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("4")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("5")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("6")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("7")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("8")
    await driver.findElement(By.id("issueDifficulty")).click()
    {
      const element = await driver.findElement(By.id("issueDifficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("issueDifficulty")).sendKeys("9")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("{(]-_|}[)")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
  })
})
