// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addTest', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addTest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Bonjour")).click()
    await driver.findElement(By.linkText("Tests")).click()
    await driver.findElement(By.linkText("Add Test")).click()
    await driver.findElement(By.id("testName")).click()
    await driver.findElement(By.id("testName")).sendKeys("Test1")
    await driver.findElement(By.id("testDescription")).click()
    await driver.findElement(By.id("testDescription")).sendKeys("Ceci est un test")
    await driver.findElement(By.css("#collapseAddTest .list-group-item:nth-child(1)")).click()
    await driver.findElement(By.id("testResult")).click()
    await driver.findElement(By.id("testResult")).sendKeys("Ceci")
    await driver.findElement(By.id("testResult")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("testResult")).sendKeys("ceci est un test")
    await driver.findElement(By.id("testValidVersion")).click()
    await driver.findElement(By.id("testValidVersion")).sendKeys("ceci est un test")
    await driver.findElement(By.css(".list-inline-item:nth-child(1) .custom-control-label")).click()
    await driver.findElement(By.css(".list-inline-item:nth-child(2) .custom-control-label")).click()
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
  })
})
