// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addTaskFailedAfterDBConnectionUpdated', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addTaskFailedAfterDBConnectionUpdated', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Manage Projects")).click()
    await driver.findElement(By.css("li:nth-child(2) .list-inline-item > .btn")).click()
    await driver.findElement(By.linkText("Tasks")).click()
    await driver.findElement(By.linkText("Ajouter tache")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Task 1")
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Test task 1")
    await driver.findElement(By.id("taskState1")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("0002-11-17")
    await driver.findElement(By.id("startDate")).sendKeys("0020-11-17")
    await driver.findElement(By.id("startDate")).sendKeys("0201-11-17")
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-17")
    await driver.findElement(By.id("new-task")).click()
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Test work")
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'User5']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'User5']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'coucou']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'User5']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'coucou']")).click()
    }
    await driver.findElement(By.id("taskRequired")).click()
    await driver.findElement(By.id("taskRequired")).click()
    await driver.findElement(By.id("taskRequired")).click()
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I3']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
  })
})
