// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('deleteProject', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('deleteProject', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Manage Projects")).click()
    await driver.findElement(By.linkText("New Project")).click()
    await driver.findElement(By.id("projectName")).click()
    await driver.findElement(By.id("projectName")).sendKeys("You will die")
    await driver.findElement(By.id("projectDescription")).click()
    await driver.findElement(By.id("projectDescription")).sendKeys("I am not sorry")
    await driver.findElement(By.css(".form-group")).click()
    await driver.findElement(By.id("usernameMemberToAdd")).click()
    await driver.findElement(By.id("usernameMemberToAdd")).sendKeys("test")
    await driver.findElement(By.css(".btn:nth-child(6)")).click()
    await driver.findElement(By.id("projectName")).click()
    await driver.findElement(By.id("projectName")).sendKeys("You will die")
    await driver.findElement(By.id("projectDescription")).click()
    await driver.findElement(By.id("projectDescription")).sendKeys("I am not sorry")
    await driver.findElement(By.id("createNewProject")).click()
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Manage Projects")).click()
    await driver.findElement(By.css("li:nth-child(3) form > .btn")).click()
    assert(await driver.switchTo().alert().getText() == "Voulez-vous vraiment supprimer ce projet ?")
    await driver.switchTo().alert().accept()
  })
})
