// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('modifyTestState', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('modifyTestState', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Bonjour")).click()
    await driver.findElement(By.linkText("Tests")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.id("passedState")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.css(".form-check:nth-child(10) > .form-check-label")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.id("failedState")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.css(".form-check:nth-child(11) > .form-check-label")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.id("failedState")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.css(".form-check:nth-child(10) > .form-check-label")).click()
    await driver.findElement(By.css(".btn-primary")).click()
  })
})
