// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('modifyTest', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('modifyTest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css(".btn-outline-success")).click()
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Bonjour")).click()
    await driver.findElement(By.linkText("Tests")).click()
    await driver.findElement(By.linkText("15: Test1")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.id("testDescription")).click()
    await driver.findElement(By.id("testName")).click()
    await driver.findElement(By.id("testName")).sendKeys("Test1 modified")
    await driver.findElement(By.id("testDescription")).click()
    await driver.findElement(By.id("testDescription")).sendKeys("Ceci est un test modified")
    await driver.findElement(By.id("testResult")).click()
    await driver.findElement(By.id("testResult")).click()
    await driver.findElement(By.id("testResult")).sendKeys("modified")
    await driver.findElement(By.id("testValidVersion")).click()
    await driver.findElement(By.id("testValidVersion")).sendKeys("modified")
    await driver.findElement(By.css(".list-inline-item:nth-child(2) .custom-control-label")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.css("#collapse15 .list-group")).click()
  })
})
