// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('modifyTaskFailedAfter;', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('modifyTaskFailedAfter;', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Bonjour")).click()
    await driver.findElement(By.linkText("Tasks")).click()
    await driver.findElement(By.css("#tasks_done .mb-1")).click()
    await driver.findElement(By.linkText("Modifier")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Test3(yeuk")
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("J^jfipezjfk,uyuky")
    await driver.findElement(By.css(".form-check:nth-child(4) > .form-check-label")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-08")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("12")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("nyj,ukiulkzfceaf")
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'Test3']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_doing > .list-group-item:nth-child(2)")).click()
    await driver.findElement(By.linkText("Modifier")).click()
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'Test3(yeuk']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'gbdvfc']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'coucou']")).click()
    }
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-24")
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Test;iy")
    await driver.findElement(By.css(".btn-primary")).click()
  })
})
