// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('removeIssueAndAddIssue', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('removeIssueAndAddIssue', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Manage Projects")).click()
    await driver.findElement(By.css("li:nth-child(2) .list-inline-item > .btn")).click()
    await driver.findElement(By.linkText("Issues")).click()
    await driver.findElement(By.css("#heading137 .badge-danger")).click()
    await driver.findElement(By.css("#collapse137 form > .btn")).click()
    assert(await driver.switchTo().alert().getText() == "Voulez-vous vraiment supprimer cette issue ?")
    await driver.switchTo().alert().accept()
    await driver.findElement(By.linkText("Add Issue")).click()
    await driver.findElement(By.id("issueName")).click()
    await driver.findElement(By.id("issueName")).sendKeys("I2 new")
    await driver.findElement(By.css(".badge:nth-child(5)")).click()
    await driver.findElement(By.id("issuePriority")).click()
    await driver.findElement(By.id("issuePriority")).sendKeys("LOW")
    await driver.findElement(By.id("issueDifficulty")).click()
    await driver.findElement(By.id("issueDifficulty")).sendKeys("1")
    await driver.findElement(By.id("issueDescription")).click()
    await driver.findElement(By.id("issueDescription")).sendKeys("I2 revived!")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.css("#heading143 > .d-block")).click()
    await driver.findElement(By.css("#collapse143 form > .btn")).click()
    assert(await driver.switchTo().alert().getText() == "Voulez-vous vraiment supprimer cette issue ?")
    await driver.switchTo().alert().accept()
  })
})
