version: '3'
services:
  web:
    build: .
    ports:
      - '8080:80'
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DATABASE=cdp_database
